language: node_js
node_js:
  - 10.16.0
  - 12.13.0

branches:
  except:
    - dev
    - /^dev-.+$/

install:
  - yarn
  - yarn add codecov --dev

script:
  - yarn run lint
  - yarn run test

after_success:
  - codecov
