version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "feat"
      prefix_development: "refactor"
      include_scope: true